# Generated by Django 5.1 on 2024-08-27 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_products_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='currentStock',
            new_name='reorderLevel',
        ),
    ]
