# Generated by Django 5.1 on 2024-09-19 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackingNumber', models.CharField(max_length=100, unique=True)),
                ('dateOrdered', models.DateField()),
                ('dateDelivered', models.DateField()),
                ('deliveryFee', models.IntegerField()),
                ('totalAmount', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('IN TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('BACKORDER', 'Backorder')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplierName', models.CharField(max_length=100, unique=True)),
                ('cellphoneNumber', models.CharField(max_length=100, unique=True)),
                ('telephoneNumber', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('pointPerson', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockRecordItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('qtyOrdered', models.IntegerField()),
                ('qtyDelivered', models.IntegerField()),
                ('total', models.IntegerField()),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('stockRecordID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stockrecord')),
            ],
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='supplierId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.supplier'),
        ),
    ]
