# Generated by Django 5.1 on 2024-10-10 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_supplier_cellphonenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrecorditem',
            name='productID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
    ]
