# Generated by Django 5.1 on 2024-10-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_stockrecorditem_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrecord',
            name='dateDelivered',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='dateOrdered',
            field=models.DateField(auto_now_add=True),
        ),
    ]
