# Generated by Django 5.1 on 2024-10-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_stockrecord_datedelivered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrecord',
            name='deliveryFee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='totalAmount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
