# Generated by Django 5.1 on 2024-10-10 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_stockrecord_deliveryfee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrecord',
            name='supplierId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.supplier'),
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='trackingNumber',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
