# Generated by Django 5.1 on 2024-10-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_stockrecord_supplierid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='backUoM',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='stock',
            name='frontUoM',
            field=models.CharField(default='', max_length=50),
        ),
    ]
