# Generated by Django 5.1 on 2024-10-17 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_stock_backuom_stock_frontuom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='frontUoM',
            new_name='displayUoM',
        ),
    ]
