# Generated by Django 5.1 on 2024-10-28 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_frontuom_stock_displayuom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockrecorditem',
            name='stockRecordID',
        ),
        migrations.RemoveField(
            model_name='stockrecorditem',
            name='productID',
        ),
        migrations.CreateModel(
            name='DeliveryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackingNumber', models.CharField(max_length=100, null=True, unique=True)),
                ('dateOrdered', models.DateField(auto_now_add=True)),
                ('dateDelivered', models.DateField(blank=True, null=True)),
                ('deliveryFee', models.IntegerField(blank=True, null=True)),
                ('totalAmount', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('TO ARRIVE', 'To Arrive'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=100)),
                ('supplierId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryRecordItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('qtyOrdered', models.IntegerField()),
                ('qtyDelivered', models.IntegerField()),
                ('total', models.IntegerField()),
                ('deliveryRecordID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.deliveryrecord')),
                ('productID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.DeleteModel(
            name='StockRecord',
        ),
        migrations.DeleteModel(
            name='StockRecordItem',
        ),
    ]
