# Generated by Django 5.1 on 2024-10-28 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_stockrecorditem_stockrecordid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryrecorditem',
            name='qtyOrdered',
        ),
    ]
