# Generated by Django 5.1 on 2024-10-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_deliveryrecorditem_qtyordered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryrecorditem',
            old_name='qtyDelivered',
            new_name='qty',
        ),
        migrations.AlterField(
            model_name='deliveryrecorditem',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
