# Generated by Django 5.1 on 2024-10-29 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_deliveryrecorditem_productid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionDate', models.DateField(auto_now_add=True)),
                ('terminalIssued', models.IntegerField()),
                ('amountDue', models.IntegerField()),
                ('discountApplicable', models.BooleanField()),
                ('finalAmount', models.IntegerField()),
                ('amountPaid', models.IntegerField()),
                ('customerChange', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TransactionItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('unitMeasurement', models.CharField(max_length=25)),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('transactionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transactions')),
            ],
        ),
    ]
