# Generated by Django 5.1 on 2024-10-29 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_transactions_transactionitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
        migrations.RenameModel(
            old_name='TransactionItems',
            new_name='TransactionItem',
        ),
    ]
