# Generated by Django 5.1 on 2024-10-29 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_transactions_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('VOIDED', 'Voided'), ('ON HOLD', 'On Hold')], default='ON HOLD', max_length=20),
        ),
        migrations.AlterField(
            model_name='deliveryrecord',
            name='status',
            field=models.CharField(choices=[('TO ARRIVE', 'To Arrive'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='TO ARRIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='terminalIssued',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=5),
        ),
    ]
