# Generated by Django 5.1 on 2024-10-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_transaction_status_alter_deliveryrecord_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amountDue',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amountPaid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='customerChange',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='finalAmount',
            field=models.IntegerField(null=True),
        ),
    ]
