# Generated by Django 5.1 on 2024-10-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_transaction_amountdue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amountDue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amountPaid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='customerChange',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='finalAmount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
