# Generated by Django 5.1 on 2024-10-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_transaction_amountdue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='terminalIssued',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1'),
        ),
    ]
