# Generated by Django 5.1 on 2024-10-29 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_transaction_terminalissued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='terminalIssued',
            field=models.CharField(choices=[('ONE', 'One'), ('TWO', 'Two'), ('THREE', 'Three')], default='One', max_length=10),
        ),
    ]
