# Generated by Django 5.1 on 2024-10-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_transaction_terminalissued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionitem',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='unitMeasurement',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
