# Generated by Django 5.1 on 2024-10-29 05:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_transactionitem_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transactionTime',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
