# Generated by Django 5.1 on 2024-10-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_remove_transaction_transactiondate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='productTotal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
