# Generated by Django 5.1 on 2024-11-12 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_transactionitem_producttotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryrecord',
            old_name='trackingNumber',
            new_name='referenceNumber',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='productId',
        ),
        migrations.AddField(
            model_name='product',
            name='stockRef',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.supplier'),
        ),
        migrations.AlterField(
            model_name='deliveryrecord',
            name='deliveryFee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryrecord',
            name='status',
            field=models.CharField(choices=[('VALIDATING', 'Validating'), ('DELIVERED', 'Delivered')], default='VALIDATING', max_length=20),
        ),
        migrations.AlterField(
            model_name='deliveryrecord',
            name='totalAmount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryrecorditem',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='deliveryrecorditem',
            name='total',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='backhouseStock',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amountDue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amountPaid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='customerChange',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='finalAmount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='productTotal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closedStock', models.IntegerField()),
                ('openStock', models.IntegerField()),
                ('toDisplayStock', models.IntegerField()),
                ('displayedStock', models.IntegerField()),
                ('damagedStock', models.IntegerField()),
                ('stockedOutQty', models.IntegerField()),
                ('stockOutDescription', models.TextField()),
                ('expiryDate', models.DateField()),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('stockID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stock')),
            ],
        ),
    ]
