# Generated by Django 5.1 on 2024-11-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_remove_product_modified_remove_stock_conversionrate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stockName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
