# Generated by Django 5.1 on 2024-11-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_stock_stockname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stockName',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
