# Generated by Django 5.1 on 2024-11-12 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_stock_stockname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stockRef',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.stock'),
        ),
    ]
