# Generated by Django 5.1 on 2024-11-12 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_product_stockref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stockRef',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stockName',
        ),
        migrations.AddField(
            model_name='stock',
            name='productId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
    ]
