# Generated by Django 5.1 on 2024-11-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_remove_product_stockref_remove_stock_stockname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='backhouseStock',
            field=models.FloatField(default=0),
        ),
    ]
