# Generated by Django 5.1 on 2024-11-12 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_stock_backhousestock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryrecord',
            name='dateOrdered',
        ),
    ]
