# Generated by Django 5.1 on 2024-11-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_alter_stockitem_expirydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='referenceNumber',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
