# Generated by Django 5.1 on 2024-11-13 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_stockitem_referencenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='productId',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
    ]
