# Generated by Django 5.1 on 2024-11-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_alter_stockitem_closedstock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveStockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpenStockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockOutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='stockOutDescription',
        ),
        migrations.AddField(
            model_name='stock',
            name='standardQuantity',
            field=models.IntegerField(default=0),
        ),
    ]
