# Generated by Django 5.1 on 2024-11-20 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_movestocklog_openstocklog_stockoutlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveStockLogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenceNumber', models.CharField(blank=True, max_length=25, null=True)),
                ('previousQty', models.IntegerField()),
                ('stocksMoved', models.IntegerField()),
                ('deliveryRecordItemID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.deliveryrecorditem')),
                ('logID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.movestocklog')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='OpenStockLogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenceNumber', models.CharField(blank=True, max_length=25, null=True)),
                ('boxesOpened', models.IntegerField()),
                ('previousQty', models.IntegerField()),
                ('qtyAdded', models.IntegerField()),
                ('deliveryRecordItemID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.deliveryrecorditem')),
                ('logID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.openstocklog')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='StockOutLogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenceNumber', models.CharField(blank=True, max_length=25, null=True)),
                ('previousQty', models.IntegerField()),
                ('stockOutQty', models.IntegerField()),
                ('stockOutDescription', models.TextField(null=True)),
                ('deliveryRecordItemID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.deliveryrecorditem')),
                ('logID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.stockoutlog')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
    ]
