# Generated by Django 5.1 on 2024-11-20 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_movestocklogitem_openstocklogitem_stockoutlogitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movestocklogitem',
            name='deliveryRecordItemID',
        ),
        migrations.RemoveField(
            model_name='openstocklogitem',
            name='deliveryRecordItemID',
        ),
        migrations.RemoveField(
            model_name='stockoutlogitem',
            name='deliveryRecordItemID',
        ),
        migrations.AddField(
            model_name='movestocklogitem',
            name='stockItemID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.stockitem'),
        ),
        migrations.AddField(
            model_name='openstocklogitem',
            name='stockItemID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.stockitem'),
        ),
        migrations.AddField(
            model_name='stockoutlogitem',
            name='stockItemID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.stockitem'),
        ),
    ]
