# Generated by Django 5.1 on 2024-11-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_remove_movestocklogitem_deliveryrecorditemid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movestocklog',
            name='status',
            field=models.CharField(choices=[('VALIDATING', 'Validating'), ('CONFRIMED', 'Confirmed')], default='VALIDATING', max_length=20),
        ),
        migrations.AddField(
            model_name='openstocklog',
            name='status',
            field=models.CharField(choices=[('VALIDATING', 'Validating'), ('CONFRIMED', 'Confirmed')], default='VALIDATING', max_length=20),
        ),
        migrations.AddField(
            model_name='stockoutlog',
            name='status',
            field=models.CharField(choices=[('VALIDATING', 'Validating'), ('CONFRIMED', 'Confirmed')], default='VALIDATING', max_length=20),
        ),
    ]
