# Generated by Django 5.1 on 2024-11-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_movestocklog_status_openstocklog_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openstocklogitem',
            name='damagedQty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movestocklog',
            name='status',
            field=models.CharField(choices=[('VALIDATING', 'Validating'), ('CONFIRMED', 'Confirmed')], default='VALIDATING', max_length=20),
        ),
        migrations.AlterField(
            model_name='openstocklog',
            name='status',
            field=models.CharField(choices=[('VALIDATING', 'Validating'), ('CONFIRMED', 'Confirmed')], default='VALIDATING', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockoutlog',
            name='status',
            field=models.CharField(choices=[('VALIDATING', 'Validating'), ('CONFIRMED', 'Confirmed')], default='VALIDATING', max_length=20),
        ),
    ]
