# Generated by Django 5.1 on 2024-11-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_openstocklogitem_damagedqty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openstocklogitem',
            name='damagedQty',
            field=models.IntegerField(default=0),
        ),
    ]
