# Generated by Django 5.1 on 2024-11-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_alter_openstocklogitem_damagedqty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openstocklogitem',
            name='damagedQty',
            field=models.IntegerField(),
        ),
    ]
