# Generated by Django 5.1 on 2024-11-25 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_alter_openstocklogitem_damagedqty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryrecorditem',
            name='productID',
        ),
        migrations.AddField(
            model_name='deliveryrecorditem',
            name='stockID',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='api.stock'),
        ),
        migrations.AddField(
            model_name='stock',
            name='supplier',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.supplier'),
        ),
    ]
