# Generated by Django 5.1 on 2024-11-28 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_remove_deliveryrecorditem_productid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='productId',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='productID',
        ),
        migrations.AddField(
            model_name='stock',
            name='stockName',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='RepackedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('barcodeNo', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('MISC', 'Miscellaneous'), ('STATIONERY', 'Stationery and Office Supplies'), ('SMOKING', 'Tobacco & Smoking Accessories'), ('HOUSE', 'Household Items'), ('HEALTH', 'Health & Beauty'), ('FROZEN', 'Frozen Foods'), ('REFRIDGERATED', 'Dairy & Refridgerated Items'), ('GROCERY', 'Grocery Items'), ('SNACKS', 'Snacks'), ('BEVERAGES', 'Beverages')], max_length=100)),
                ('unitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wsmq', models.IntegerField()),
                ('wsp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reorderLevel', models.IntegerField()),
                ('created', models.DateField(auto_now_add=True)),
                ('stock', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.stock')),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='productID',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
    ]
