# Generated by Django 5.1 on 2024-11-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_remove_product_supplier_remove_stock_productid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repackedproduct',
            name='unitWeight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
