# Generated by Django 5.1 on 2024-12-01 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_rename_productid_stock_productid'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepackProductLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('VALIDATING', 'Validating'), ('CONFIRMED', 'Confirmed')], default='VALIDATING', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='repackedproduct',
            name='displayedStock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliveryrecorditem',
            name='stockID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stock'),
        ),
        migrations.CreateModel(
            name='RepackProductLogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenceNumber', models.CharField(blank=True, max_length=25, null=True)),
                ('boxesOpened', models.IntegerField()),
                ('previousQty', models.IntegerField()),
                ('qtyAdded', models.IntegerField()),
                ('damagedQty', models.IntegerField()),
                ('logID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.openstocklog')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.repackedproduct')),
                ('stockItemID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.stockitem')),
            ],
        ),
    ]
