# Generated by Django 5.1 on 2024-12-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_rename_repackproductlog_repackstocklog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openrepackstocklogitem',
            name='qtyAdded',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
