# Generated by Django 5.1 on 2024-12-02 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_remove_openrepackstocklogitem_productid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openrepackstocklogitem',
            name='logID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.openrepackstocklog'),
        ),
    ]
