# Generated by Django 5.1 on 2024-12-02 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_alter_openrepackstocklogitem_logid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openrepackstocklogitem',
            name='openedStock',
            field=models.IntegerField(),
        ),
    ]
