# Generated by Django 5.1 on 2024-12-02 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_alter_stockitem_openstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repackstocklogitem',
            name='damagedQty',
        ),
        migrations.RemoveField(
            model_name='repackstocklogitem',
            name='previousQty',
        ),
        migrations.AddField(
            model_name='repackstocklogitem',
            name='qtyUsed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
