# Generated by Django 5.1 on 2024-12-02 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_remove_repackstocklogitem_damagedqty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repackstocklogitem',
            name='logID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.repackstocklog'),
        ),
    ]
