# Generated by Django 5.1 on 2024-12-02 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_alter_repackstocklogitem_logid'),
    ]

    operations = [
        migrations.AddField(
            model_name='repackstocklogitem',
            name='stockID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.stock'),
            preserve_default=False,
        ),
    ]
