# Generated by Django 5.1 on 2024-12-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_repackstocklogitem_stockid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='damagedStock',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
