# Generated by Django 5.1 on 2024-12-02 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_alter_stockitem_damagedstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repackedproductstockoutlogitem',
            name='logID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.repackedproductstockoutlog'),
        ),
    ]
