# Generated by Django 5.1 on 2024-12-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_remove_transactionitem_productid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returns',
            name='refundAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
