# Generated by Django 5.1 on 2024-12-03 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_alter_returns_refundamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnitems',
            name='amountRefundable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='returnitems',
            name='itemPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
