# Generated by Django 5.1 on 2024-12-03 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_alter_returnitems_transactionitemid'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndCashCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateToday', models.DateField(auto_now_add=True, unique=True)),
                ('thousand', models.IntegerField()),
                ('fiveHundred', models.IntegerField()),
                ('twoHundred', models.IntegerField()),
                ('oneHundred', models.IntegerField()),
                ('fifty', models.IntegerField()),
                ('twenty', models.IntegerField()),
                ('ten', models.IntegerField()),
                ('five', models.IntegerField()),
                ('one', models.IntegerField()),
                ('twoFiveCent', models.IntegerField()),
                ('tenCent', models.IntegerField()),
                ('oneCent', models.IntegerField()),
                ('amountTotal', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StartCashCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateToday', models.DateField(auto_now_add=True, unique=True)),
                ('beginningBalance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
        ),
    ]
