# Generated by Django 5.1 on 2024-12-03 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_endcashcount_startcashcount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endcashcount',
            old_name='oneCent',
            new_name='fiveCent',
        ),
    ]
